### PR TITLE
Docs: Update CI sample files to use newer CI environments and PowerShell 7

### PR DESCRIPTION
**Pull request by joeltimothyoh**

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
lgtm

**Comment by leojonathanoh** [comment]
@joeltimothyoh  how about using https://hub.docker.com/r/microsoft/powershell/ images directly, and using github workflows? azure pipelines is old

**Comment by joeltimothyoh** [comment]
Possible, but those are clean images that don't contain packages such as `git` for resolving of paths of submodules, or `sudo` for installation of dependencies in CI environments. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh could use https://github.com/theohbrothers/docker-powershell, see some examples https://github.com/theohbrothers/Get-DuplicateItem/blob/v1.1.2/.github/workflows/ci-master-pr.yml#L121

**Comment by joeltimothyoh** [comment]
> why need sudo? job already running as root

`sudo` was necessary for installing certain packages within containers as the container user in `azure-pipelines`. I believe container jobs are initialized to run as a user regardless of their pre-configurations. `sudo` was thus required for running commands such as `apt-get`. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh guess the images should be built with those packages so there would be no need for `apt-get` in ci jobs

**Comment by joeltimothyoh** [comment]
@leojonathanoh most of them would likely already exist within the provided VM images. But if steps are run within containers access to those tools would require installation. Could build images to contain those packages. But that adds severe overhead. Besides, PS cmdlets could be used in many ways which could involve any number of package combinations. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh e.g. of an external package that PS needs outisde of the PS libraries?

**Comment by joeltimothyoh** [comment]
Or `build`, test, or `publish` time dependencies that superprojects require. @leojonathanoh

**Comment by joeltimothyoh** [comment]
Here's logs from the past demonstrating the need for the `sudo` package in container jobs on azure-pipelines:

# Without `sudo`

- https://dev.azure.com/startersclan/Compile-SourceScript/_build/results?buildId=205&view=logs&j=6f12d3be-437a-59bf-0616-36fdeef4a6be&t=8b3a2719-f521-5850-1793-8e98a2339e22&l=265 - https://github.com/startersclan/Compile-SourceScript/blob/d650daf334e9ac722b23d04dcb6ede98b23a6516/test/Install-TestDependencies.ps1#L18-L28

This was an issue in spite of what `Initialize containers` step logs claim: https://dev.azure.com/startersclan/Compile-SourceScript/_build/results?buildId=205&view=logs&j=6f12d3be-437a-59bf-0616-36fdeef4a6be&t=7f1bce06-ff30-4fc9-af32-50ddb862b235&l=65

# With `sudo` package and invoking `sudo`

- with `sudo` command: https://dev.azure.com/startersclan/Compile-SourceScript/_build/results?buildId=206&view=logs&j=6f12d3be-437a-59bf-0616-36fdeef4a6be&t=8b3a2719-f521-5850-1793-8e98a2339e22&l=268 - https://github.com/startersclan/Compile-SourceScript/blob/65f6bbe0a1c53ae5b2391f53917f58459667df79/test/Install-TestDependencies.ps1#L25-L36

# In sum

The docs on container jobs did address some requirements for docker images used in container jobs. The requirements could have changed now: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops. GitLab doesn't seem to have the same issue. Things could have changed for azure-pipelines since. Just a heads-up concerning container jobs and possible need for the `sudo` package. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh move on to github actions might not have such an issue

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh move on to github actions might not have such an issue

I would think so. Never really had a use case for mutating container images other than the above so I don't know. @leojonathanoh

**Comment by joeltimothyoh** [comment]
The lack of log retention is a serious downside of GHA. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh the poor disintegrated azp system is also a pretty major downside

**Pull request merged**
